name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: '13'
        postgresql db: 'test_db'
        postgresql user: 'test_user'
        postgresql password: 'test_password'

    - name: Apply migrations
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      run: python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      run: python manage.py test